### ISSUE TITLE
Indicate non-obvious logic

### ISSUE THREAD

**Issue by kbranch** [kbranch/Magpie#20]
The main issue here is the entrances that can act as connectors, e.g. the pits in bird key cave, the hole in Lanmola's room and the hole near D7 that leads to damp cave. An indicator that these exist would be helpful.

This might also extend to things like drop downs that people often forget about - it can be hard to understand how certain areas are in logic.

**Comment by foxsouns** [comment]
I recall being the reason this issue was made, hehe :3
The lanmola cave drop, imo, should be an entrance with its check attached: probably in the same list that lanmola uses. also, its' exit is useful in entrance rando: these exits are definitely in logic, as lanmola cave exit was the only way of progression in one of my recent seeds.

**Comment by kbranch** [comment]
Hmm, maybe when ER is off, the default connector behavior should be shown. That plus some mspaint lines doodled on the map image for things like the Kanalet access via rooster might go a long way.

**Comment by kbranch** [comment]
This is finally in, although the list of things that get shown could probably stand to get longer.
